### ISSUE TITLE
Accept custom schema in `use SwissSchema` [Blocked]

### ISSUE THREAD

**Issue by joeljuca** [joeljuca/swiss_schema#4]
I've been thinking about making SwissSchema able to generate schema functions in other modules than the target schema itself. The use case is to allow it to be used in ctx modules.

Something like that:

```ex
# accounts.ex

defmodule MyApp.Accounts do
  use SwissSchema,
    schema: MyApp.Accounts.User
end
```

This way, SwissSchema could be used to replace generated ctx functions, resulting in cleaner ctx modules.

**Comment by mohammedzeglam-pg** [comment]
Maybe it be like
```elixir
defmodule MyApp.Accounts do
  use SwissSchema,
    schema: [user: MyApp.Accounts.User, token: MyApp.Accounts.Token]
end
```

**Comment by joeljuca** [comment]
Hi @mohammedzeglam-pg,

What role do you think the `:token` keyword should play?

**Comment by mohammedzeglam-pg** [comment]
> Hi @mohammedzeglam-pg,
> 
> What role do you think the `:token` keyword should play?

generate function name not all context relay on one schema could context use 2-3 different schema

```elixir
MyApp.Accuonts.get_user/1
MyApp.Accounts.get_token/1
```

**Comment by joeljuca** [comment]
@mohammedzeglam-pg I see!

Interesting idea. So far, I've considered SwissSchema functions for a single schema only, but if it's going to be used in context modules it might be a good idea to inject functions for multiple schemas.

I'll think more about how the API should look if it will support multiple schemas per context. Thanks for the suggestion!

**Comment by mohammedzeglam-pg** [comment]
> @mohammedzeglam-pg I see!
> 
> Interesting idea. So far, I've considered SwissSchema functions for a single schema only, but if it's going to be used in context modules it might be a good idea to inject functions for multiple schemas.
> 
> I'll think more about how the API should look if it will support multiple schemas per context. Thanks for the suggestion!

Maybe run different function as phoenix do with ~:controller~ ~:live_view~ ...etc

and could you consider review #6

**Comment by joeljuca** [comment]
I thought about this issue and the scope of this project, and I realized it's not a good idea to extend SwissSchema to such scenarios. SwissSchema should be about having queryable Ecto schemas, not generating functions in context modules.

This should not be implemented, but it's worth a PR to include this decision in `FAQ.md`. I'm leaving it open until I get some free time to do it right.
